import express from 'express';
import dbAsync from '../../db.js';
import { authenticateAdminToken } from '../../middleware/auth.js';
import { isPlainObject, sendError, sendSuccess } from '../../utils/api.js';
const router=express.Router(); const valid=v=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(String(v||''));
const pub=r=>({id:r.id,slug:r.slug,title:r.title,shortDescription:r.short_description,description:r.description,startsAt:r.starts_at,endsAt:r.ends_at,facilityId:r.facility_id,locationText:r.location_text,coverImageUrl:r.cover_image_url,featured:Boolean(r.is_featured),displayOrder:r.display_order});
const admin=r=>({...pub(r),status:r.status});
async function save(req,res,create){const b=req.body||{},old=create?null:await dbAsync.get('SELECT * FROM events WHERE id=? OR slug=?',[req.params.identifier,req.params.identifier]);if(!create&&!old)return sendError(res,404,'Event not found.');const id=create?String(b.id||''):old.id,slug=String(b.slug??old?.slug??'').trim().toLowerCase(),title=String(b.title??old?.title??'').trim(),start=String(b.startsAt??old?.starts_at??''),end=b.endsAt??old?.ends_at??null,status=String(b.status??old?.status??'draft');if(!isPlainObject(b)||!valid(id)||!valid(slug)||title.length<2||title.length>255||!start||Number.isNaN(Date.parse(start))||(end&&Number.isNaN(Date.parse(end)))||(end&&Date.parse(end)<Date.parse(start))||!['draft','active','inactive'].includes(status))return sendError(res,400,'Event data is invalid.');try{await dbAsync.run('INSERT INTO events (id,slug,title,short_description,description,starts_at,ends_at,facility_id,location_text,cover_image_url,status,is_featured,display_order,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT (id) DO UPDATE SET slug=EXCLUDED.slug,title=EXCLUDED.title,short_description=EXCLUDED.short_description,description=EXCLUDED.description,starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at,facility_id=EXCLUDED.facility_id,location_text=EXCLUDED.location_text,cover_image_url=EXCLUDED.cover_image_url,status=EXCLUDED.status,is_featured=EXCLUDED.is_featured,display_order=EXCLUDED.display_order,updated_at=CURRENT_TIMESTAMP)',[id,slug,title,b.shortDescription??old?.short_description??null,b.description??old?.description??null,start,end,b.facilityId??old?.facility_id??null,b.locationText??old?.location_text??null,b.coverImageUrl??old?.cover_image_url??null,status,b.featured?1:0,Number(b.displayOrder??old?.display_order??0)]);return sendSuccess(res,{event:admin(await dbAsync.get('SELECT * FROM events WHERE id=?',[id]))},create?201:200)}catch(e){return sendError(res,/UNIQUE/.test(e.message)?409:500,'Unable to save event.')}}
router.get('/',async(_q,s)=>{try{return sendSuccess(s,{events:(await dbAsync.all("SELECT * FROM events WHERE status='active' ORDER BY is_featured DESC,display_order,starts_at")).map(pub)})}catch{return sendError(s,500,'Unable to load events.')}});router.get('/admin/all',authenticateAdminToken,async(_q,s)=>sendSuccess(s,{events:(await dbAsync.all('SELECT * FROM events ORDER BY display_order,starts_at')).map(admin)}));router.post('/admin/events',authenticateAdminToken,(q,s)=>save(q,s,true));router.put('/admin/events/:identifier',authenticateAdminToken,(q,s)=>save(q,s,false));router.get('/:identifier',async(q,s)=>{const r=await dbAsync.get("SELECT * FROM events WHERE (id=? OR slug=?) AND status='active'",[q.params.identifier,q.params.identifier]);return r?sendSuccess(s,{event:pub(r)}):sendError(s,404,'Event not found.')});export default router;
